FROM nginx:1.26.0

# Copy the HTML and CSS files to the container
COPY ./web /usr/share/nginx/html

# Expose port 80 for HTTP traffic
EXPOSE 80

# Start the nginx server
CMD ["nginx", "-g", "daemon off;"]